services:

  file_storage:
    class: Sokil\FileStorageBundle\FileStorage
    arguments:
      - '@doctrine.orm.default_entity_manager'
      - '@knp_gaufrette.filesystem_map'

  file_storage.repository.file_repository:
    class: Sokil\FileStorageBundle\Repository\FileRepositoy
    factory_service: doctrine.orm.default_entity_manager
    factory_method: getRepository
    arguments:
      - Sokil\FileStorageBundle\Entity\File

  file_storage.adapter.internal.pathstrategy.chunkpath:
    class: Sokil\FileStorageBundle\GaufretteAdapter\Internal\PathStrategy\ChunkPathStrategy
    arguments:
      - {chunksNumber: 2, chunkSize: 3, preserveExtension: false}

  file_storage.gaufrette.adapter.internal:
    class: Sokil\FileStorageBundle\GaufretteAdapter\Internal
    arguments:
      - '@file_storage.repository.file_repository'
      - '@file_storage.adapter.internal.pathstrategy.chunkpath'
    abstract: true
    public: false
