services:

  file_storage:
    class: Sokil\FileStorageBundle\FileStorage
    arguments:
      - '@doctrine.orm.default_entity_manager'
      - '@knp_gaufrette.filesystem_map'

  file_storage.gaufrette.adapter.internal.pathStrategy.chunkPath:
    class: Sokil\FileStorageBundle\GaufretteAdapter\Internal\PathStrategy\ChunkPathStrategy
    arguments:
      - {chunksNumber: 2, chunkSize: 3, preserveExtension: false}

  file_storage.gaufrette.adapter.internal:
    class: Sokil\FileStorageBundle\GaufretteAdapter\Internal
    arguments:
      - '@file_storage.gaufrette.adapter.internal.pathStrategy.chunkPath'
    abstract: true
    public: false
